debug tikv
Signed-off-by: Jianjun Liao <jianjun.liao@outlook.com>

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -137,16 +137,17 @@ kv_outage() {
         done
         # let tikv start up completely if backup is finished before tikv restarts
         ensure_tikv
+        for i in "${id[@]}"; do
+            debug_tikv "$i"
+        done
         # sometimes even though a tikv node is stopped, pd also show is_intialized in ensure_tikv
         sleep 1
     }
 }
 
 debug_tikv() {
-    for i in $(seq $TIKV_COUNT); do
-        echo "Debug TiKV($i)..."
-        run_curl "https://$TIKV_STATUS_ADDR$i/debug/dup-key/disable" "{}"
-    done    
+    echo "Debug TiKV($i)..."
+    run_curl "https://$TIKV_STATUS_ADDR$i/debug/dup-key/disable" "{}" || echo "failed to disable debug dup key"
 }
 
 start_tikv() {
@@ -175,7 +176,6 @@ ensure_tikv() {
        fi
        sleep 5
     done
-    debug_tikv
 }
 
 start_tidb() {
@@ -242,6 +242,9 @@ start_services_impl() {
         start_tikv "$i"
     done
     ensure_tikv
+    for i in $(seq $TIKV_COUNT); do
+        debug_tikv "$i"
+    done
     if $RUN_TIDB; then
         start_tidb
     fi
